name: gru_gcn

periods: 10
weight_decay: 1e-3
clip_grad_max_norm: 0.5

model:
  _target_: src.GRU_GCN.GRU_GCN_Model
  #num_nodes: -1 # NOTE: will set from dataset
  input_dim: 10
  embed_dim: 32
  gru_hidden_dim: 64
  gcn_hidden_dim: 64
  output_dim: 2
  num_layers: 1
  dropout: 0.4
  probability_of_selecting_nodes: -1 # NOTE: will set from dataset
  num_nodes: -1 # NOTE: will set from dataset
  return_temporal_mask: True
